[project]
name = "thesunset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astral>=3.2",
    "boto3>=1.38.42",
    "ipython>=9.3.0",
    "opencv-python>=4.12.0.88",
    "pytz>=2025.2",
    "schedule>=1.2.2",
]
